[package]
name = "juniper_resistance"
version = "0.1.0"
authors = ["davidroeca"]

[dependencies]
juniper = "0.9.0"
juniper_rocket = "0.1.2"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
diesel = { version = "1.1.1", features = ["postgres", "r2d2"] }
dotenv = "0.9.0"
